In [6]:
import pandas as pd
import numpy as np

In [67]:
df = pd.read_csv('./savecsv.csv')

In [69]:
df

,stress_score,sleep_hours,working_hours,free_time,holidays_per_year,stress
0,12,8,10,4,3,0
1,15,5,12,5,1,0
2,18,7,10,2,2,1
3,21,10,5,5,0,1
4,27,1,10,1,0,1
5,15,8,10,2,1,0
6,16,7,9,2,1,0
7,17,7,8,1,1,0
8,18,8,9,2,1,1
9,16,6,10,3,2,0
10,15,7,11,2,1,0
11,19,8,12,2,0,0
12,19,8,10,3,0,0
13,18,7,9,5,0,0
14,19,8,10,6,1,0
15,20,8,10,5,2,1
16,21,6,11,4,1,1
17,18,6,10,5,0,1
18,17,7,8,4,0,1
19,17,6,8,5,0,1
20,18,8,8,5,1,1
21,19,6,7,6,2,0
22,20,5,8,6,1,0
23,18,6,10,6,1,0
24,20,7,12,4,2,0
25,21,5,11,3,1,1
26,22,6,10,3,1,1
27,23,5,12,2,0,1
28,22,6,12,3,0,1
29,23,5,12,2,0,1
...,...,...,...,...,...,...
69,26,1,16,0,0,1
70,24,2,14,0,0,1
71,24,3,14,0,0,1
72,24,3,15,0,0,1
73,24,4,15,0,0,1
74,23,2,15,0,0,1
75,23,3,14,2,0,1
76,24,3,14,1,0,10
77,23,2,13,2,0,0
78,22,3,11,3,1,0
79,22,4,11,1,2,1
80,22,3,10,2,1,1
81,22,3,9,1,2,1
82,21,4,9,3,1,0
83,22,8,9,2,1,0
84,25,2,13,3,1,0
85,25,8,13,0,2,0
86,23,3,12,1,0,1
87,22,8,10,2,0,1
88,22,7,8,1,0,1
89,21,6,8,2,0,1
90,21,6,7,1,2,1
91,20,5,8,2,2,1
92,19,6,9,3,2,1
93,19,8,8,3,1,0
94,19,9,7,3,1,0
95,18,8,6,2,2,0
96,18,8,7,3,1,0
97,15,7,8,4,3,0
98,16,8,6,6,3,0

In [74]:
def modify(x) :
    max = 27.0
    return (x/max)*21.0

In [78]:
type(df['stress_score'][1])

numpy.int64

In [75]:
for i in range(np_df.shape[0]) :
    df['stress_score'][i] = modify(df['stress_score'][i])

In [89]:
df.to_csv('save2csv.csv',header=True , index = False)

In [90]:
p = pd.read_csv('./save2csv.csv')

In [91]:
p.head()

,stress_score,sleep_hours,working_hours,free_time,holidays_per_year,stress
0,9,8,10,4,3,0
1,11,5,12,5,1,0
2,14,7,10,2,2,1
3,16,10,5,5,0,1
4,21,1,10,1,0,1

# MODIFYING COLUMN VALUES

In [63]:
# cols = df.columns
# for c in cols :
#     print c

# np_df = np.asarray(df)
# def modify(x) :
#     max = 27.0
#     return (x/max)*21.0
# for i in range(np_df.shape[0]) :
#     np_df[i,0] = modify(np_df[i,0])
# print len(cols)
# final = {}
# for i in range(len(cols)) :
#     final[cols[i]] = np_df[:,i]
# pd_final = pd.DataFrame(final)

,free_time,holidays_per_year,sleep_hours,stress,stress_score,working_hours
0,4,3,8,0,9,10
1,5,1,5,0,11,12
2,2,2,7,1,14,10
3,5,0,10,1,16,5
4,1,0,1,1,21,10
5,2,1,8,0,11,10
6,2,1,7,0,12,9
7,1,1,7,0,13,8
8,2,1,8,1,14,9
9,3,2,6,0,12,10
10,2,1,7,0,11,11
11,2,0,8,0,14,12
12,3,0,8,0,14,10
13,5,0,7,0,14,9
14,6,1,8,0,14,10
15,5,2,8,1,15,10
16,4,1,6,1,16,11
17,5,0,6,1,14,10
18,4,0,7,1,13,8
19,5,0,6,1,13,8
20,5,1,8,1,14,8
21,6,2,6,0,14,7
22,6,1,5,0,15,8
23,6,1,6,0,14,10
24,4,2,7,0,15,12
25,3,1,5,1,16,11
26,3,1,6,1,17,10
27,2,0,5,1,17,12
28,3,0,6,1,17,12
29,2,0,5,1,17,12
...,...,...,...,...,...,...
69,0,0,1,1,20,16
70,0,0,2,1,18,14
71,0,0,3,1,18,14
72,0,0,3,1,18,15
73,0,0,4,1,18,15
74,0,0,2,1,17,15
75,2,0,3,1,17,14
76,1,0,3,10,18,14
77,2,0,2,0,17,13
78,3,1,3,0,17,11
79,1,2,4,1,17,11
80,2,1,3,1,17,10
81,1,2,3,1,17,9
82,3,1,4,0,16,9
83,2,1,8,0,17,9
84,3,1,2,0,19,13
85,0,2,8,0,19,13
86,1,0,3,1,17,12
87,2,0,8,1,17,10
88,1,0,7,1,17,8
89,2,0,6,1,16,8
90,1,2,6,1,16,7
91,2,2,5,1,15,8
92,3,2,6,1,14,9
93,3,1,8,0,14,8
94,3,1,9,0,14,7
95,2,2,8,0,14,6
96,3,1,8,0,14,7
97,4,3,7,0,11,8
98,6,3,8,0,12,6